### ISSUE TITLE
[Bug]: Do not release source file to npm

### ISSUE THREAD

**Issue by himself65** [Portkey-AI/portkey-node-sdk#138]
### Contact Details

alex@runllama.ai

### What happened?

for 1.x, you release all repo to npm

### Version

0.1.xx (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by csgulati09** [comment]
Hey! 

Can you please explain the what exactly is the issue here?

**Comment by himself65** [comment]
You guys didn't publish to npm correctly:

https://www.npmjs.com/package/portkey-ai?activeTab=code

1. in package.json, it's `"main": "dist/src/index.js",` but it actually doesn't exist. because you didn't build the proejct and publish it

<img width="1292" alt="image" src="https://github.com/user-attachments/assets/abb86d38-caf6-404f-96d1-08d73f25d203">

<img width="368" alt="image" src="https://github.com/user-attachments/assets/ce6fc118-4798-4cc4-925d-d8637c3b536f">

**Comment by himself65** [comment]
0.1.16 is the last correct version

**Comment by csgulati09** [comment]
Thanks for pointing this out. Looking into this.

**Comment by csgulati09** [comment]
Hey! 
This seems to be alright. As the path mentioned do exists: 
<img width="518" alt="image" src="https://github.com/user-attachments/assets/6dcfce74-e787-4e1b-b159-51872e81a090">
