### ISSUE TITLE
Type Errors bubbling up to project

### ISSUE THREAD

**Issue by HisWordLLC** [Portkey-AI/portkey-node-sdk#24]
https://github.com/Portkey-AI/portkey-node-sdk/blob/56d1911739a8201811b69bfad04d56728a281b9a/src/index.ts#L7

I don't know if others have experienced this, but I'm getting a Type Error bubbling up to the project level:

```
> tsc

node_modules/portkey-ai/dist/src/index.ts:7:1 - error TS1269: Cannot use 'export import' on a type or type-only namespace when 'isolatedModules' is enabled.

7 export import LLMOptions = Types.LLMOptions;
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/portkey-ai/dist/src/index.ts:7
```

Will just ignore type checking in builds for now. Let me know if you want a PR to assist. 👍

**Comment by VisargD** [comment]
Thanks for reporting this and also providing detailed errors. We will push a fix for this today

**Comment by HisWordLLC** [comment]
Thanks for the fast reply, @VisargD 

Really enjoying the service so far. Have some small UI papercuts in the platform that I can submit if it helps. Let me know a good place to do so.

**Comment by VisargD** [comment]
That's so good to hear!! You can join our discord and report the UI feedback their. Here is our discord link: https://t.co/lZEFk6kbbb

**Comment by VisargD** [comment]
That's so good to hear!! You can join our discord and report the UI feedback there. Here is our discord link: https://t.co/lZEFk6kbbb

**Comment by VisargD** [comment]
The ideal solution here would have been to change the re-export to support types in isolatedModules which would have made the export something like this (as mentioned [here in TS docs](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export)):

```
export type { LLMOptions } from "./_types/portkeyConstructs";
```

But the `LLMOptions` interface itself is deprecated now and we do not support it anymore. So we will be removing the interface and export itself. I will be merging the PR for this very soon.

**Comment by VisargD** [comment]
This issue has been fixed in the latest release of the SDK. Please update version to 1.1.3 and try it out.

**Comment by gdibble** [comment]
@VisargD I noticed the churn/reversion and wanted to say thanks for your efforts!

I've run `yarn upgrade portkey-ai@^1.1.3` and can confirm on my project that nextjs can [again/now] build. ✅

**Comment by VisargD** [comment]
That's great! Thanks for the confirmation.

**Comment by VisargD** [comment]
Closing this issue as it is resolved now. Feel free to create a new one if you have other queries. Thanks again for reporting and providing details.

**Comment by HisWordLLC** [comment]
Just updated and tested. All works great! Thanks for the quick solve. 😃
