### ISSUE TITLE
[Bug]: TS Compile Issue in Yarn

### ISSUE THREAD

**Issue by SimonPringleWallace** [Portkey-AI/portkey-node-sdk#56]
### Contact Details

s.pringlewallace@gmail.com

### What happened?

After installing the node-sdk into a React project and running `yarn start` I'm receiving the following output. Granted, for demo purposes I am attempting to integrate this into a React app rather than a more typical Node implementation so my use case on its own may account for the issue. Any insight you could provide would be most appreciated!

### Version

0.1.xx (Default)

### Relevant log output

```shell
webpack compiled successfully
ERROR in node_modules/portkey-ai/dist/src/apis/assistants.ts:209:56
TS2339: Property 'files' does not exist on type 'Assistants'.
    207 |         });
    208 |     
  > 209 |         const result = await OAIclient.beta.assistants.files.create(assistantId, body, opts).withResponse();
        |                                                        ^^^^^
    210 |
    211 |         return finalResponse(result);
    212 |     }

ERROR in node_modules/portkey-ai/dist/src/apis/assistants.ts:261:56
TS2339: Property 'files' does not exist on type 'Assistants'.
    259 |         });
    260 |     
  > 261 |         const result = await OAIclient.beta.assistants.files.retrieve(assistantId, fileId, opts).withResponse();
        |                                                        ^^^^^
    262 |
    263 |         return finalResponse(result);
    264 |     } 

ERROR in node_modules/portkey-ai/dist/src/apis/assistants.ts:286:56
TS2339: Property 'files' does not exist on type 'Assistants'.
    284 |         });
    285 |     
  > 286 |         const result = await OAIclient.beta.assistants.files.del(assistantId, fileId, opts).withResponse();
        |                                                        ^^^^^
    287 |
    288 |         return finalResponse(result);
    289 |     } 

ERROR in node_modules/portkey-ai/dist/src/apis/threads.ts:319:62
TS2339: Property 'files' does not exist on type 'Messages'.
    317 |         });
    318 |     
  > 319 |         const result = await OAIclient.beta.threads.messages.files.retrieve(threadId, messageId, fileId, opts).withResponse();
        |                                                              ^^^^^
    320 |
    321 |         return finalResponse(result);
    322 |     }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonPringleWallace** [comment]
Update: I believe this is related to my use of OpenAI's Assistants API, which I don't believe is supported by Portkey as of yet.

**Comment by vrushankportkey** [comment]
Thank you for raising this @SimonPringleWallace. This is happening because of the [latest changes by OpenAI to the Assistants API](https://platform.openai.com/docs/assistants/whats-new). 

We are actively working on fixing this on priority #58

**Comment by SimonPringleWallace** [comment]
Thank you for the update! Appreciate you all getting this fixed so quickly.

**Comment by unicolored** [comment]
Hello! I have the same build issue.

Is there a workaround until the bug is fixed?

**Comment by VisargD** [comment]
Hey. Sorry for the delay here. We are releasing a new version in a hour which should solve this issue.

**Comment by unicolored** [comment]
Indeed @VisargD ! No more build issue :D
Congrats on the release!
