### ISSUE TITLE
Deprecation warning for `punycode`

### ISSUE THREAD

**Issue by vrushankportkey** [Portkey-AI/portkey-node-sdk#83]
Getting this warning when running a typescript code:

(node:3624) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.

**Comment by AshrithSathu** [comment]
Hey mostly this issue occurs when you use the node js version which is not long term supported , if nvm is installed revert it to the latest LTS support version and this shouldn't occur

**Comment by csgulati09** [comment]
Closing this issue as Portkey SDK is not directly depending on punycode. 
While looking into it, this is not a breaking change and it is mostly dependent on the Node version of the user as mentioned by @AshrithSathu
